export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_TIMER = 'AUTH_LOGOUT_TIMER';

export const LOAD_MENU_START = 'LOAD_MENU_START';
export const LOAD_MENU_SUCCESS = 'LOAD_MENU_SUCCESS';
export const LOAD_MENU_FAIL = 'LOAD_MENU_FAIL';

export const ADMIN_ADD_CREPE_START = 'ADMIN_ADD_CREPE_START';
export const ADMIN_ADD_CREPE_SUCCESS = 'ADMIN_ADD_CREPE_SUCCESS';
export const ADMIN_ADD_CREPE_FAIL = 'ADMIN_ADD_CREPE_FAIL';
export const ADMIN_ADD_CREPE_RESET = 'ADMIN_ADD_CREPE_RESET';

export const ADMIN_DELETE_CREPE_START = 'ADMIN_DELETE_CREPE_START';
export const ADMIN_DELETE_CREPE_SUCCESS = 'ADMIN_DELETE_CREPE_SUCCESS';
export const ADMIN_DELETE_CREPE_FAIL = 'ADMIN_DELETE_CREPE_FAIL';
export const ADMIN_DELETE_CREPE_RESET = 'ADMIN_DELETE_CREPE_RESET';

export const ADMIN_ADD_INGREDIENT_START = 'ADMIN_ADD_INGREDIENT_START';
export const ADMIN_ADD_INGREDIENT_SUCCESS = 'ADMIN_ADD_INGREDIENT_SUCCESS';
export const ADMIN_ADD_INGREDIENT_FAIL = 'ADMIN_ADD_INGREDIENT_FAIL';

export const ADMIN_DELETE_INGREDIENT_START = 'ADMIN_DELETE_INGREDIENT_START';
export const ADMIN_DELETE_INGREDIENTNU_SUCCESS = 'ADMIN_DELETE_INGREDIENTNU_SUCCESS';
export const ADMIN_DELETE_INGREDIENT_FAIL = 'ADMIN_DELETE_INGREDIENT_FAIL';
