export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_TIMER = 'AUTH_LOGOUT_TIMER';

export const LOAD_CREPES_START = 'LOAD_CREPES_START';
export const LOAD_CREPES_SUCCESS = 'LOAD_CREPES_SUCCESS';
export const LOAD_CREPES_FAIL = 'LOAD_CREPES_FAIL';

export const ADMIN_ADD_CREPE_START = 'ADMIN_ADD_CREPE_START';
export const ADMIN_ADD_CREPE_SUCCESS = 'ADMIN_ADD_CREPE_SUCCESS';
export const ADMIN_ADD_CREPE_FAIL = 'ADMIN_ADD_CREPE_FAIL';
export const ADMIN_ADD_CREPE_RESET = 'ADMIN_ADD_CREPE_RESET';

export const ADMIN_CREPE_NAME_CHANGED = 'ADMIN_CREPE_NAME_CHANGED';
export const ADMIN_ADD_INGREDIENT_TO_CREPE = 'ADMIN_ADD_INGREDIENT_TO_CREPE';
export const ADMIN_REMOVE_INGREDIENT_TO_CREPE = 'ADMIN_REMOVE_INGREDIENT_TO_CREPE';
export const ADMIN_INIT_INGREDIENTS_TO_CREPE = 'ADMIN_INIT_INGREDIENTS_TO_CREPE';

export const ADMIN_LOAD_CREPE_START = 'ADMIN_LOAD_CREPE_START';
export const ADMIN_LOAD_CREPE_SUCCESS = 'ADMIN_LOAD_CREPE_SUCCESS';
export const ADMIN_LOAD_CREPE_FAIL = 'ADMIN_LOAD_CREPE_FAIL';
export const ADMIN_SYNCHRO_INGREDIENTS_TO_CREPE = 'ADMIN_SYNCHRO_INGREDIENTS_TO_CREPE';

export const ADMIN_EDIT_CREPE_START = 'ADMIN_EDIT_CREPE_START';
export const ADMIN_EDIT_CREPE_SUCCESS = 'ADMIN_EDIT_CREPE_SUCCESS';
export const ADMIN_EDIT_CREPE_FAIL = 'ADMIN_EDIT_CREPE_FAIL';

export const ADMIN_DELETE_CREPE_START = 'ADMIN_DELETE_CREPE_START';
export const ADMIN_DELETE_CREPE_SUCCESS = 'ADMIN_DELETE_CREPE_SUCCESS';
export const ADMIN_DELETE_CREPE_FAIL = 'ADMIN_DELETE_CREPE_FAIL';
export const ADMIN_DELETE_CREPE_RESET = 'ADMIN_DELETE_CREPE_RESET';

export const ADMIN_ADD_INGREDIENT_START = 'ADMIN_ADD_INGREDIENT_START';
export const ADMIN_ADD_INGREDIENT_SUCCESS = 'ADMIN_ADD_INGREDIENT_SUCCESS';
export const ADMIN_ADD_INGREDIENT_FAIL = 'ADMIN_ADD_INGREDIENT_FAIL';
export const ADMIN_ADD_INGREDIENT_RESET = 'ADMIN_ADD_INGREDIENT_RESET';

export const ADMIN_INGREDIENT_NAME_CHANGED = 'ADMIN_INGREDIENT_NAME_CHANGED';
export const ADMIN_INGREDIENT_QUANTITY_CHANGED = 'ADMIN_INGREDIENT_QUANTITY_CHANGED';

export const ADMIN_LOAD_INGREDIENT_START = 'ADMIN_LOAD_INGREDIENT_START';
export const ADMIN_LOAD_INGREDIENT_SUCCESS = 'ADMIN_LOAD_INGREDIENT_SUCCESS';
export const ADMIN_LOAD_INGREDIENT_FAIL = 'ADMIN_LOAD_INGREDIENT_FAIL';

export const ADMIN_EDIT_INGREDIENT_START = 'ADMIN_EDIT_INGREDIENT_START';
export const ADMIN_EDIT_INGREDIENT_SUCCESS = 'ADMIN_EDIT_INGREDIENT_SUCCESS';
export const ADMIN_EDIT_INGREDIENT_FAIL = 'ADMIN_EDIT_INGREDIENT_FAIL';

export const ADMIN_DELETE_INGREDIENT_START = 'ADMIN_DELETE_INGREDIENT_START';
export const ADMIN_DELETE_INGREDIENT_SUCCESS = 'ADMIN_DELETE_INGREDIENT_SUCCESS';
export const ADMIN_DELETE_INGREDIENT_FAIL = 'ADMIN_DELETE_INGREDIENT_FAIL';
export const ADMIN_DELETE_INGREDIENT_RESET = 'ADMIN_DELETE_INGREDIENT_RESET';

export const LOAD_INGREDIENTS_START = 'LOAD_INGREDIENTS_START';
export const LOAD_INGREDIENTS_SUCCESS = 'LOAD_INGREDIENTS_SUCCESS';
export const LOAD_INGREDIENTS_FAIL = 'LOAD_INGREDIENTS_FAIL';

export const LOAD_CUSTOMIZED_CREPE = 'LOAD_CUSTOMIZED_CREPE';
export const RESET_CUSTOMIZED_CREPE = 'RESET_CUSTOMIZED_CREPE';
export const MORE_INGREDIENT_FOR_CREPE = 'MORE_INGREDIENT_FOR_CREPE';
export const LESS_INGREDIENT_FOR_CREPE = 'LESS_INGREDIENT_FOR_CREPE';
export const REMOVE_INGREDIENT_FOR_CREPE = 'REMOVE_INGREDIENT_FOR_CREPE';
export const ADD_INGREDIENT_FOR_CREPE = 'ADD_INGREDIENT_FOR_CREPE';
export const CHANGE_CURRENT_ADDITIONAL_INGREDIENT = 'CHANGE_CURRENT_ADDITIONAL_INGREDIENT';
export const LOAD_ORDER_CREPE = 'LOAD_ORDER_CREPE';

export const ADD_CREPE_TO_ORDER = 'ADD_CREPE_TO_ORDER';
export const REMOVE_CREPE_TO_ORDER = 'REMOVE_CREPE_TO_ORDER';
export const RESET_FLASH_MESSAGE_FOR_ORDER = 'RESET_FLASH_MESSAGE_FOR_ORDER';
export const TIMER_FLASH_MESSAGE_FOR_ORDER = 'TIMER_FLASH_MESSAGE_FOR_ORDER';
