export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_TIMER = 'AUTH_LOGOUT_TIMER';

export const LOAD_MENU_START = 'LOAD_MENU_START';
export const LOAD_MENU_SUCCESS = 'LOAD_MENU_SUCCESS';
export const LOAD_MENU_FAIL = 'LOAD_MENU_FAIL';

export const ADD_CREPE_TO_MENU_START = 'ADD_CREPE_TO_MENU_START';
export const ADD_CREPE_TO_MENU_SUCCESS = 'ADD_CREPE_TO_MENU_SUCCESS';
export const ADD_CREPE_TO_MENU_FAIL = 'ADD_CREPE_TO_MENU_FAIL';

export const DELETE_CREPE_FROM_MENU_START = 'DELETE_CREPE_FROM_MENU_START';
export const DELETE_CREPE_FROM_MENU_SUCCESS = 'DELETE_CREPE_FROM_MENU_SUCCESS';
export const DELETE_CREPE_FROM_MENU_FAIL = 'DELETE_CREPE_FROM_MENU_FAIL';
